/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EntitiesTableIndexRouteImport } from './routes/entities/$table/index'
import { Route as EntitiesTablePkRouteImport } from './routes/entities/$table/$pk'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesTableIndexRoute = EntitiesTableIndexRouteImport.update({
  id: '/entities/$table/',
  path: '/entities/$table/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesTablePkRoute = EntitiesTablePkRouteImport.update({
  id: '/entities/$table/$pk',
  path: '/entities/$table/$pk',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entities/$table/$pk': typeof EntitiesTablePkRoute
  '/entities/$table/': typeof EntitiesTableIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entities/$table/$pk': typeof EntitiesTablePkRoute
  '/entities/$table': typeof EntitiesTableIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/entities/$table/$pk': typeof EntitiesTablePkRoute
  '/entities/$table/': typeof EntitiesTableIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/entities/$table/$pk' | '/entities/$table/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/entities/$table/$pk' | '/entities/$table'
  id: '__root__' | '/' | '/entities/$table/$pk' | '/entities/$table/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EntitiesTablePkRoute: typeof EntitiesTablePkRoute
  EntitiesTableIndexRoute: typeof EntitiesTableIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/$table/': {
      id: '/entities/$table/'
      path: '/entities/$table'
      fullPath: '/entities/$table/'
      preLoaderRoute: typeof EntitiesTableIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/$table/$pk': {
      id: '/entities/$table/$pk'
      path: '/entities/$table/$pk'
      fullPath: '/entities/$table/$pk'
      preLoaderRoute: typeof EntitiesTablePkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EntitiesTablePkRoute: EntitiesTablePkRoute,
  EntitiesTableIndexRoute: EntitiesTableIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
